LIST(APPEND TOOLKIT_SMESH
        SMDSAbs
        SMESH
        SMDS
        SMESHDS
        StdMeshers
)
if (PYTHONOCC_WRAP_NETGEN)
  SET(TOOLKIT_SMESH ${TOOLKIT_SMESH} NETGENPlugin)
endif()  
if (PYTHONOCC_WRAP_TETGEN)
  SET(TOOLKIT_SMESH ${TOOLKIT_SMESH} TetgenPlugin)
endif()  
